name: just
base: core20
version: '1.2.0'
summary: Just a command runner
description: |
  just is a handy way to save and run project-specific commands.

grade: stable
confinement: classic

apps:
  just:
    command: bin/just

parts:
  just:
    source: https://github.com/casey/just/archive/refs/tags/1.2.0.tar.gz
    plugin: rust
